# Generated by Django 5.2.15 on 2026-08-23 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sifen_code', models.PositiveIntegerField(unique=True, verbose_name='SIFEN code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sifen_code', models.PositiveIntegerField(unique=True, verbose_name='SIFEN code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='locations.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sifen_code', models.PositiveIntegerField(unique=True, verbose_name='SIFEN code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='locations.district', verbose_name='District')),
            ],
            options={
                'verbose_name': 'City / Locality',
                'verbose_name_plural': 'Cities / Localities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sifen_code', models.PositiveIntegerField(unique=True, verbose_name='SIFEN code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='neighborhoods', to='locations.city', verbose_name='City / Locality')),
            ],
            options={
                'verbose_name': 'Neighborhood',
                'verbose_name_plural': 'Neighborhoods',
                'ordering': ['name'],
            },
        ),
    ]
