# Generated by Django 4.2.30 on 2026-08-23 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demo_addresses', to='locations.city')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demo_addresses', to='locations.department')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demo_addresses', to='locations.district')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demo_addresses', to='locations.neighborhood')),
            ],
            options={
                'ordering': ['label', 'id'],
            },
        ),
    ]
